### ISSUE TITLE
Previously wrapped formplate DOM elements are rewrapped

### ISSUE THREAD

**Issue by hopkinschris** [chrishumboldt/Formplate#19]
I'm using Formplate in a Backbone.js project and I've noticed when new elements (which use Formplate) are rendered and appended into the DOM in which Formplate has already be instantiated the plugin rewraps those previously existing elements. In the case of checkboxes you get double wrapped `<span class='fp-checkbox'>...</span>` elements.

I introduced this change into my version:

````
			// Checkboxes
			$('.formplate input[type="checkbox"]').each(function()
			{
				if($(this).hasClass('toggler'))
				{
					// Don't rewrap previous formplate DOM elements
					if($(this).parents('.fp-toggler').length === 0)
					{
						// Wrap input
						$(this).wrap('<span class="fp-toggler"></span>');

						// Check state
						if($(this).is(':checked'))
						{
							$(this).parents('.fp-toggler').addClass('checked');
						}
					}
				}
				else
				{
					// Don't rewrap previous formplate DOM elements
					if($(this).parents('.fp-checkbox').length === 0)
					{
						// Wrap input
						$(this).wrap('<span class="fp-checkbox"></span>');

						// Check state
						if($(this).is(':checked'))
						{
							$(this).parents('.fp-checkbox').addClass('checked');
						}
					}
				}
			});
````

This may be inherit to only my case, so if you think this is an outlier situation feel free to mark this as a `wontfix` but I thought I would make a note of it here in case it's beneficial to anyone :)

**Comment by chrishumboldt** [comment]
This has been resolved.
