### ISSUE TITLE
Update main in bower.json file

### ISSUE THREAD

**Issue by artivilla** [chrishumboldt/Formplate#26]
Hey,

I'm trying to install your package via bower.json but the main directory is listing compiled files which means I can't import your plugin into my application's main scss file. Also, I think bower suggests these are entry files: http://bower.io/docs/creating-packages/. Can you update those to include the following. I'd make pull request but it's 2 simple lines:

```
"main": [
    "sass/formplate.scss",
    "js/formplate.min.js" 
  ],
```

**Comment by chrishumboldt** [comment]
For now the component import in Webplate (for which this is a base component) uses these files in the inclusion method. You will need to change the file references manually for now until I can find a better solution. I agree with your comment though and will let you know should a change be made.
